# Mémoire pour gradle (la décompilation de Minecraft en demande pas mal).
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environnement

# La version de Minecraft doit correspondre à la version de Forge.
minecraft_version=1.19.2
minecraft_version_range=[1.19.2,1.20)
forge_version=43.4.4
forge_version_range=[43,)
loader_version_range=[43,)
# Mappings officiels Mojang.
mapping_channel=official
mapping_version=1.19.2


## Le mod

mod_id=cubelandmetiers
mod_name=Cubeland Métiers
mod_license=Tous droits réservés - Cubeland
mod_version=2.0.0
mod_group_id=fr.cubeland
mod_authors=Cubeland
mod_description=Les six métiers de Cubeland : mineur, bûcheron, fermier, chasseur, pêcheur et cuisinier. La cuisine en cinq paliers, le carnet et ses commandes.
