# Memoire pour gradle (la decompilation de Minecraft en demande pas mal).
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environnement

# La version de Minecraft doit correspondre a la version de Forge.
minecraft_version=1.19.2
minecraft_version_range=[1.19.2,1.20)
forge_version=43.4.4
forge_version_range=[43,)
loader_version_range=[43,)
# Mappings officiels Mojang.
mapping_channel=official
mapping_version=1.19.2


## Le mod

mod_id=cubelandmetiers
mod_name=Cubeland Metiers
mod_license=Tous droits reserves - Cubeland
mod_version=1.4.2
mod_group_id=fr.cubeland
mod_authors=Cubeland
mod_description=Les six metiers de Cubeland : mineur, bucheron, fermier, chasseur, pecheur et cuisinier.
